<?php

namespace AppBundle\Repository\Pokemon;

/**
 * UserPokemonStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPokemonStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
